spm:
  - url: git@github.com:krzyzanowskim/CryptoSwift.git
    from: 1.4.1
    path: 
    search-paths: []
    linked-libs: []

search-paths: []
linked-libs: []


ios:
  name: UgCryptoSwift
  id: com.scade.UgCryptoSwift
  device-family: iphone # iphone, ipad or universal
  supported-interface-orientations: ['portrait'] # portrait, upside_down, landscape_left or landscape_right
  supported-interface-orientationsiPad: ['portrait']
  entitlements-file: 
  app-delegate-file:
  simulator:
    os: 12.1
    output: UgCryptoSwift/.build/ios-simulator
    extra-args:
    search-paths: []
    linked-libs: []
    spm:
      dependencies:
        - name: CryptoSwift
  device: 
    os: 12.1
    output: UgCryptoSwift/.build/ios-device
    product-path: UgCryptoSwift/Product/ios-device
    extra-args: 
    search-paths: []
    linked-libs: []
    spm:
      dependencies:
        - name: CryptoSwift
  mac:
    os: 10.11
    output: UgCryptoSwift/.build/scade-simulator
    product-path: UgCryptoSwift/Product/scade-simulator
    extra-args: 
    search-paths: []
    linked-libs: []
    spm:
      dependencies:
        - name: CryptoSwift
  sign:
    provision-profile:
    certificate:
    beta-reports-active: false
  icons: 
    iphone: # or ipad, sizes: 20X20, 29X29, 40X40, 60X60, 76X76, 83.5X83.5
      60X60_2X:
      76X76_2X:
      76X76_3X:
      83.5X83.5_2X:
    marketing:
      1024X1024_1X:
  plist: 
    - key: CFBundleShortVersionString
      type: string  # string, bool, int, list or dict
      value: 1.0
    - key: CFBundleVersion
      type: string
      value: 1
    - key: NSLocationWhenInUseUsageDescription
      type: string
      value: 
    - key: NSCameraUsageDescription
      type: string
      value: Take pictures from camera
    - key: NSPhotoLibraryUsageDescription
      type: string
      value: Choose a photo from your library

android:
  name: UgCryptoSwift
  id: com.scade.UgCryptoSwift
  version-name: 1.0.0
  version-code: 1
  build-type: Debug
  key-store-properties:
  google-api-key: 
  manifest-file:
  permissions: []
  armeabi-v7a:
    output: UgCryptoSwift/.build/android-armeabi-v7a
    product-path: UgCryptoSwift/Product/android-armeabi-v7a
    extra-args:
    search-paths: []
    linked-libs: []
    spm:
      dependencies:
        - name: CryptoSwift
  x86:
    output: UgCryptoSwift/.build/android-x86
    product-path: UgCryptoSwift/Product/android-x86
    extra-args:
    search-paths: []
    linked-libs: []
    spm:
      dependencies:
        - name: CryptoSwift
  arm64-v8a:
    output: UgCryptoSwift/.build/android-arm64-v8a
    product-path: UgCryptoSwift/Product/android-arm64-v8a
    extra-args:
    search-paths: []
    linked-libs: []
    spm:
      dependencies:
        - name: CryptoSwift
  x86_64:
    output: UgCryptoSwift/.build/android-x86_64
    product-path: UgCryptoSwift/Product/android-x86_64
    extra-args:
    search-paths: []
    linked-libs: []
    spm:
      dependencies:
        - name: CryptoSwift
  intent-filters:
    - action:
      scheme:
      categories: [] 
  icons:
    mdpi:
    hdpi:
    xhdpi: 
    xxhdpi:
