spm:
  - url: git@github.com:nicklockwood/Expression.git
    from: 0.13.2
    path: 
    search-paths: []
    linked-libs: []

search-paths: []
linked-libs: []

ios:
  name: UgCalculator
  id: com.scade.UgCalculator
  device-family: iphone # iphone, ipad or universal
  supported-interface-orientations: ['portrait'] # portrait, upside_down, landscape_left or landscape_right
  supported-interface-orientationsiPad: ['portrait']
  entitlements-file: 
  app-delegate-file:
  simulator:
    os: 12.1
    output: UgCalculator/.build/ios-simulator
    product-path: UgCalculator/Product/ios-simulator
    extra-args:
    search-paths: []
    linked-libs: []
    spm:
      dependencies:
        - name: Expression
          package: Expression
  device: 
    os: 12.1
    output: UgCalculator/.build/ios-device
    product-path: UgCalculator/Product/ios-device
    extra-args: 
    search-paths: []
    linked-libs: []
    spm:
      dependencies:
        - name: Expression
          package: Expression
  mac:
    os: 10.11
    output: UgCalculator/.build/scade-simulator
    extra-args: 
    search-paths: []
    linked-libs:
    spm:
      dependencies:
        - name: Expression
          package: Expression
  sign:
    provision-profile:
    certificate:
    beta-reports-active: false
  icons: 
    iphone: # or ipad, sizes: 20X20, 29X29, 40X40, 60X60, 76X76, 83.5X83.5
      60X60_2X: Assets/icons/Calculator-icon.png
      76X76_2X: Assets/icons/Calculator-icon.png
      76X76_3X: Assets/icons/Calculator-icon.png
      83.5X83.5_2X: Assets/icons/Calculator-icon.png
    marketing:
      1024X1024_1X:
  plist: 
    - key: CFBundleShortVersionString
      type: string  # string, bool, int, list or dict
      value: 1.0
    - key: CFBundleVersion
      type: string
      value: 1
    - key: NSLocationWhenInUseUsageDescription
      type: string
      value: 
    - key: NSCameraUsageDescription
      type: string
      value: Take pictures from camera
    - key: NSPhotoLibraryUsageDescription
      type: string
      value: Choose a photo from your library

android:
  name: UgCalculator
  id: com.scade.UgCalculator
  version-name: 1.0.0
  version-code: 1
  build-type: Debug
  key-store-properties: ${env.UGEXAMPLES_ANDROID_KEYSTORE_PROPERTIES}
  google-api-key: 
  manifest-file:
  permissions: []
  armeabi-v7a:
    output: UgCalculator/.build/android-armeabi-v7a
    product-path: UgCalculator/Product/android-armeabi-v7a
    extra-args:
    search-paths: []
    linked-libs:
    spm:
      dependencies:
        - name: Expression
          package: Expression
  x86:
    output: UgCalculator/.build/android-x86
    product-path: UgCalculator/Product/android-x86
    extra-args:
    search-paths: []
    linked-libs:
    spm:
      dependencies:
        - name: Expression
          package: Expression
  arm64-v8a:
    output: UgCalculator/.build/android-arm64-v8a
    product-path: UgCalculator/Product/android-arm64-v8a
    extra-args:
    search-paths: []
    linked-libs:
    spm:
      dependencies:
        - name: Expression
          package: Expression
  x86_64:
    output: UgCalculator/.build/android-x86_64
    product-path: UgCalculator/Product/android-x86_64
    extra-args:
    search-paths: []
    linked-libs:
    spm:
      dependencies:
        - name: Expression
          package: Expression
  intent-filters:
    - action:
      scheme:
      categories: [] 
  icons:
    mdpi: Assets/icons/Calculator-icon.png
    hdpi: Assets/icons/Calculator-icon.png
    xhdpi: Assets/icons/Calculator-icon.png
    xxhdpi: Assets/icons/Calculator-icon.png
